version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI:

  database:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
