version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://admin:password@localhost"

  database:
    image: mongo:4.2-bionic
    environment:
	  MONGO_INITDB_ROOT_USERNAME: "admin"
	  MONGO_INITDB_ROOT_PASSWORD: "password"
	  MONGO_INITDB_DATABASE: "Diddle_North"
	volumes:
	  - mongo_data:./mongo-init.js:/data/parking-lot

volumes:
  mongo_data:
